apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'prod'
multiTarget:
  targetIds: [ 'main-service-prod', 'download-package-service-prod', 'fetch-directory-service-prod', 'fetch-history-service-prod', 'ingest-package-service-prod', 'query-cost-service-prod', 'rate-package-service-prod', 'reset-system-service-prod', 'search-package-service-prod', 'update-package-service-prod', 'upload-package-service-prod' ]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'main-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'download-package-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'fetch-directory-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'fetch-history-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'ingest-package-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'query-cost-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'rate-package-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'reset-system-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'search-package-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'update-package-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'upload-package-service-prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'