apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'dev'
multiTarget:
  targetIds: [ 'main-service-dev', 'download-package-service-dev', 'fetch-directory-service-dev', 'fetch-history-service-dev', 'ingest-package-service-dev', 'query-cost-service-dev', 'rate-package-service-dev', 'reset-system-service-dev', 'search-package-service-dev', 'update-package-service-dev', 'upload-package-service-dev' ]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'main-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'download-package-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'fetch-directory-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'fetch-history-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'ingest-package-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'query-cost-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'rate-package-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'reset-system-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'search-package-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'update-package-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'upload-package-service-dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'