apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: 'reset-system-service-pipeline'
serialPipeline:
  stages:
    - targetId: 'dev'
      profiles: ['dev']
    - targetId: 'staging'
      profiles: ['staging']
    - targetId: 'prod'
      profiles: ['prod']
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'dev'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'staging'
run:
  location: 'projects/package-registry-team11/locations/us-central1'
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: 'prod'
run:
  location: 'projects/package-registry-team11/locations/us-central1'