name: 'Build rate-package-service-prod image and deploy to Cloud Run'

on:
  pull_request:
    types:
      - 'closed'
    branches:
      - 'prod'
    paths:
      - 'app-server/services/rate-package-service/**'

env:
  PROJECT_ID: 'package-registry-team11'
  REGION: 'us-central1'
  SERVICE: 'rate-package-service-prod'
  GAR_REPO: 'rate-package-service-prod'
  SRC_PATH: 'app-server/services/rate-package-service'

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.prod

      - name: 'Build and push container image'
        run: |-
          docker build -t "${{ env.REGION }}-docker.pkg.prod/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}.image:${{ github.sha }}" "${{ env.SRC_PATH }}"
          docker push "${{ env.REGION }}-docker.pkg.prod/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}.image:${{ github.sha }}"

      - name: 'Deploy to Cloud Run'
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: '${{ env.REGION }}-docker.pkg.prod/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ env.SERVICE }}.image:${{ github.sha }}'